[build-system]
requires = [
    "setuptools >= 61.0"
]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src/"]
include = ["phx.fix", "phx.fix.app", "phx.fix.model", "phx.fix.tracker", "phx.fix.utils", "phx.utils"]

[project]
name = "phx-fix-base"